chore: update license and improve linting

diff --git a/zarf.yaml b/zarf.yaml
--- a/zarf.yaml
+++ b/zarf.yaml
@@ -1,3 +1,6 @@
+# Copyright 2026 Defense Unicorns
+# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
+
 # yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
 
 kind: ZarfPackageConfig
@@ -7,73 +10,73 @@ metadata:
   url: https://github.com/defenseunicorns/uds-k3d
   yolo: true
   # x-release-please-start-version
-  version: "0.20.1"
+  version: 0.20.1
   # x-release-please-end
 
 variables:
   - name: CLUSTER_NAME
-    description: "Name of the cluster"
-    default: "uds"
+    description: Name of the cluster
+    default: uds
 
   - name: K3D_IMAGE
-    description: "K3d image to use"
+    description: K3d image to use
     # renovate: datasource=docker depName=rancher/k3s versioning=semver
-    default: "ghcr.io/defenseunicorns/uds-k3d/k3s:v1.35.5-k3s1"
+    default: ghcr.io/defenseunicorns/uds-k3d/k3s:v1.35.5-k3s1
 
   - name: K3D_ULIMIT_NOFILE
     description: "Set ulimit for the number of files (nofile) to container runtime (Format: SOFT:HARD)"
-    default: "1048576:1048576"
+    default: 1048576:1048576
 
   - name: K3D_EXTRA_ARGS
-    description: "Optionally pass k3d arguments to the default"
+    description: Optionally pass k3d arguments to the default
     default: ""
 
   - name: K3D_DEBUG
-    description: "Enable debug mode for k3d"
+    description: Enable debug mode for k3d
     default: "false"
 
   - name: NGINX_EXTRA_PORTS
-    description: "Optionally allow more ports through Nginx (combine with K3D_EXTRA_ARGS '-p <port>:<port>@server:*')"
+    description: Optionally allow more ports through Nginx (combine with K3D_EXTRA_ARGS '-p <port>:<port>@server:*')
     default: "[]"
 
   - name: DOMAIN
-    description: "Cluster domain"
-    default: "uds.dev"
+    description: Cluster domain
+    default: uds.dev
 
   - name: ADMIN_DOMAIN
-    description: "Domain for admin services, defaults to `admin.DOMAIN`"
+    description: Domain for admin services, defaults to `admin.DOMAIN`
 
   - name: K3D_API_PORT
-    description: "Kubernetes API server port for the cluster"
+    description: Kubernetes API server port for the cluster
     default: "6550"
 
   - name: K3D_HTTP_PORT
-    description: "HTTP port mapping for the cluster"
+    description: HTTP port mapping for the cluster
     default: "80"
 
   - name: K3D_HTTPS_PORT
-    description: "HTTPS port mapping for the cluster"
+    description: HTTPS port mapping for the cluster
     default: "443"
 
   - name: K3D_NETWORK
-    description: "Network to join k3d cluster to"
+    description: Network to join k3d cluster to
     default: ""
 
 components:
   - name: destroy-cluster
     required: true
-    description: "Optionally destroy the cluster before creating it"
+    description: Optionally destroy the cluster before creating it
     actions:
       onDeploy:
         before:
-          - cmd: k3d cluster delete ${ZARF_VAR_CLUSTER_NAME}
-            description: "Destroy the cluster"
+          - cmd: k3d cluster delete "${ZARF_VAR_CLUSTER_NAME}"
+            description: Destroy the cluster
 
   - name: k3d-airgap-images
     required: true
     only:
       flavor: airgap
-    description: "Load the airgap images for k3d into Docker"
+    description: Load the airgap images for k3d into Docker
     import:
       path: airgap/k3d
       name: k3d-airgap-images
@@ -95,26 +98,26 @@ components:
               echo "###################################################"
               echo ""
           - cmd: echo "true"
-            description: "Set AIRGAP_MODE to true"
+            description: Set AIRGAP_MODE to true
             mute: true
             setVariables:
               - name: AIRGAP_MODE
 
   - name: create-cluster
     required: true
-    description: "Create the k3d cluster"
+    description: Create the k3d cluster
     actions:
       onDeploy:
         before:
           - cmd: |
               k3d_version=$(k3d version | grep -E -o "([0-9]+\.?){3}$")
               required_version="5.7.1"
-              if ! printf "$required_version\n$k3d_version" | sort -V -c 2>/dev/null; then
+              if ! printf '%s\n%s' "$required_version" "$k3d_version" | sort -V -c 2>/dev/null; then
                 echo "This package requires a minimum k3d version of $required_version"
                 echo "Please upgrade k3d (https://k3d.io/stable/#install-current-latest-release) and try again"
                 exit 1
               fi
-            description: "Check k3d version compatibility"
+            description: Check k3d version compatibility
           - cmd: |
               VOLUME_MOUNT=""
               if [ "${ZARF_VAR_AIRGAP_MODE}" = "true" ]; then
@@ -138,10 +141,11 @@ components:
               if [ -n "${ZARF_VAR_K3D_NETWORK}" ]; then
                 NETWORK="--network ${ZARF_VAR_K3D_NETWORK}"
               fi
+              # shellcheck disable=SC2086
               k3d cluster create \
-                ${HTTP_PORT} \
-                ${HTTPS_PORT} \
-                --api-port ${ZARF_VAR_K3D_API_PORT} \
+                "${HTTP_PORT}" \
+                "${HTTPS_PORT}" \
+                --api-port "${ZARF_VAR_K3D_API_PORT}" \
                 --runtime-ulimit nofile="${ZARF_VAR_K3D_ULIMIT_NOFILE}" \
                 --k3s-arg "--disable=traefik@server:*" \
                 --k3s-arg "--disable=metrics-server@server:*" \
@@ -149,22 +153,22 @@ components:
                 --k3s-arg "--disable=local-storage@server:*" \
                 --k3s-arg "--kube-cloud-controller-manager-arg=requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt@server:*" \
                 --k3s-arg "--kube-cloud-controller-manager-arg=client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt@server:*" \
-                --image ${ZARF_VAR_K3D_IMAGE} \
+                --image "${ZARF_VAR_K3D_IMAGE}" \
                 ${ZARF_VAR_K3D_EXTRA_ARGS} \
-                ${NETWORK} \
+                "${NETWORK}" \
                 ${DEBUG_FLAGS} \
-                ${VOLUME_MOUNT} \
-                ${ZARF_VAR_CLUSTER_NAME}
-            description: "Create the cluster"
+                "${VOLUME_MOUNT}" \
+                "${ZARF_VAR_CLUSTER_NAME}"
+            description: Create the cluster
         onSuccess:
           # Wait for CoreDNS to be available. This allows slow internet connections to complete before we move on and try to connect to a cluster that may or may not be ready to accept connections. CoreDNS is a deployment we can trust will always be there.
           - wait:
               cluster:
                 kind: Pod
                 condition: Ready
-                name: "k8s-app=kube-dns"
+                name: k8s-app=kube-dns
                 namespace: kube-system
-            description: "Wait for CoreDNS to be ready"
+            description: Wait for CoreDNS to be ready
           - cmd: |
               echo "You can access this cluster over SSH:"
               echo "ssh -N -L ${ZARF_VAR_K3D_HTTP_PORT}:localhost:${ZARF_VAR_K3D_HTTP_PORT} -L ${ZARF_VAR_K3D_HTTPS_PORT}:localhost:${ZARF_VAR_K3D_HTTPS_PORT} -L ${ZARF_VAR_K3D_API_PORT}:localhost:${ZARF_VAR_K3D_API_PORT} user@remote-host"
@@ -174,37 +178,37 @@ components:
               echo
               echo "This cluster can be destroyed with:"
               echo "k3d cluster delete ${ZARF_VAR_CLUSTER_NAME}"
-            description: "Print out information about how to access the cluster remotely"
+            description: Print out information about how to access the cluster remotely
 
   - name: uds-dev-stack-airgap-images
     required: true
     only:
       flavor: airgap
-    description: "Load the airgap images for uds-dev-stack into Docker"
+    description: Load the airgap images for uds-dev-stack into Docker
     import:
       path: airgap/uds-dev-stack
       name: uds-dev-stack-airgap-images
 
   - name: uds-dev-stack
     required: true
-    description: "Install MetalLB, NGINX, Minio, local-path-rwx and Ensure MachineID to meet UDS developer needs without later config changes"
+    description: Install MetalLB, NGINX, Minio, local-path-rwx and Ensure MachineID to meet UDS developer needs without later config changes
     actions:
       onDeploy:
         before:
           - cmd: ./zarf tools kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}' | cut -d'.' -f1-3
-            description: "Load network ip base for MetalLB"
+            description: Load network ip base for MetalLB
             setVariables:
               - name: BASE_IP
         after:
           - cmd: ./zarf tools kubectl rollout restart deployment coredns -n kube-system
-            description: "Restart CoreDNS to pick up internal DNS override for uds.dev"
+            description: Restart CoreDNS to pick up internal DNS override for uds.dev
     charts:
       - name: metallb
         namespace: kube-system
         url: https://metallb.github.io/metallb
         version: 0.16.1
         valuesFiles:
-          - "values/metallb-values.yaml"
+          - values/metallb-values.yaml
       - name: uds-dev-stack
         namespace: kube-system
         localPath: chart
@@ -212,15 +216,15 @@ components:
         version: 0.20.1
         # x-release-please-end
         valuesFiles:
-          - "values/dev-stack-values.yaml"
+          - values/dev-stack-values.yaml
         variables:
           - name: COREDNS_OVERRIDES
             # Defaults contain rewrites of `*.uds.dev` to the UDS core Istio tenant and admin gateways
-            description: "CoreDNS overrides"
+            description: CoreDNS overrides
             path: coreDnsOverrides
       - name: minio
         namespace: uds-dev-stack
         version: 5.4.0
         url: https://charts.min.io/
         valuesFiles:
-          - "values/minio-values.yaml"
+          - values/minio-values.yaml
